name: Unit test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    # Fix GitHub Actions crashing with:
    # CRASH: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g"

    steps:
      - name: Checkout GIT
        uses: actions/checkout@v2

      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      #----------------------------------------------------

      #Optimization
      - name: Enable Gradle Wrapper caching (optimization)
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      #---------------------------------------------------

      # RUN
      - name: Unit test
        run: ./gradlew testDebugUnitTest
      #------------------------------------------------------------------
